/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.yedekparca;

import admin.gorevli.adminGorevli;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Objects;
import javax.swing.JOptionPane;
import superr.admin.superAdmin;

/**
 *
 * @author Bireysel
 */
public class Giris extends javax.swing.JFrame {

    /**
     * Creates new form Giris
     */
    public Giris() {
        initComponents();

        ArrayList<Integer> d1 = new ArrayList<>();
        ArrayList<Integer> d2 = new ArrayList<>();

        for (int i = 0; i < 5; i++) {
            d1.add(i);
        }

        d2.add(0);
        d2.add(8);
        d2.add(7);
        d2.add(6);
        d2.add(5);

        Collections.sort(d1);
        Collections.sort(d2);

        int k1 = d1.get(0);
        int k2 = d2.get(0);
        for (int i = 0; true; i++) {
            k1 = d1.get(i);
            k2 = d2.get(i);
            if (k1 == k2) {
                if (d1.get(i + 1) > d2.get(i + 1)) {
                    k1 = d2.get(i + 1);
                } else {
                    k1 = d1.get(i + 1);
                }
            }
            break;
        }

        // 0,1,2,3,4
        // 0,5,6,7,8
        int toplam = k1 + k2;
        System.out.println("Toplam : " + toplam);

        //int[] dm = new int[1000];
        ArrayList<Integer> ml = new ArrayList<>();
        for (int i = 1; i <= 1000; i++) {
            ml.add(1);
        }

        // yorumlar
        /*
        l : for (int i = 0; true; i++) {

            if (ml.size() > i + 1) {
                ml.set(i + 1, 0);
            }
            for (int j = 0; j < ml.size(); j++) {
                if (ml.get(j) == 1) {
                    if (j > 1) {
                        break l;
                    } else {
                        System.out.println("Son Eleman : " + i);
                    }
                
            }

        }
    }
        */

        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKulAdi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtKulSifre = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin Giriş");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Admin Giriş Paneli"));

        jLabel1.setText("Kullanıcı Adı :");

        jLabel2.setText("Şifre");

        txtKulAdi.setText("veli");
        txtKulAdi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKulAdiKeyPressed(evt);
            }
        });

        jButton1.setText("Giriş Yap");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtKulSifre.setText("veli");
        txtKulSifre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKulSifreKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtKulAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtKulSifre)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKulAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKulSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        girisYap();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtKulAdiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKulAdiKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            girisYap();
        }
    }//GEN-LAST:event_txtKulAdiKeyPressed

    private void txtKulSifreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKulSifreKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            girisYap();
        }
    }//GEN-LAST:event_txtKulSifreKeyPressed

    private void girisYap() {

        String kuladi = txtKulAdi.getText().trim().toLowerCase();
        String sifre = String.valueOf(txtKulSifre.getPassword()).trim().toLowerCase();

        if (kuladi.equals("")) {
            txtKulAdi.requestFocus();
            JOptionPane.showMessageDialog(this, "Lütfen Kullanıcı adınızı giriniz !");
        } else if (sifre.equals("")) {
            txtKulSifre.requestFocus();
            JOptionPane.showMessageDialog(this, "Lütfen Şifre giriniz !");
        } else {
            String pasmd5 = Common.MD5(sifre);
            try {
                ResultSet rs = new MYSQLDB().baglan().executeQuery("select *from admin where akuladi = '" + kuladi + "' and asifre = '" + pasmd5 + "'");
                if (rs.next()) {
                    // kullanıcı girişi başarılıdır
                    Common.aid = rs.getString("aid");
                    Common.aadi = rs.getString("aadi");
                    Common.asoyadi = rs.getString("asoyadi");
                    Common.akuladi = rs.getString("akuladi");
                    Common.seviye = rs.getString("seviye");
                    Common.atarih = rs.getString("atarih");
                    if (rs.getString("seviye").equals("0")) {
                        // admin aç
                        adminGorevli adg = new adminGorevli();
                        adg.setVisible(true);
                        this.setVisible(false);
                    }

                    if (rs.getString("seviye").equals("1")) {
                        // süper admin aç
                        superAdmin spa = new superAdmin();
                        spa.setVisible(true);
                        this.setVisible(false);
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Kullanıcı adı yada şifre hatalı");
                }
            } catch (Exception e) {
                System.err.println("SQL hatası : " + e);
            }

        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Giris.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Giris.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Giris.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Giris.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Giris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtKulAdi;
    private javax.swing.JPasswordField txtKulSifre;
    // End of variables declaration//GEN-END:variables
}
