/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin.gorevli;

import com.yedekparca.MYSQLDB;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bireysel
 */
public class SatisRaporu extends javax.swing.JFrame {

    /**
     * Creates new form SatisRaporu
     */
    public SatisRaporu() {
        initComponents();
        satisRaporuDataGetir();
        satisRaporuToplamDataGetir();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRaporla = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSatisRapor = new javax.swing.JTable();
        lblToplamFiyat = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Satış Raporu");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Satış Raporu"));

        jLabel1.setText("Başlangıç");

        jLabel2.setText("Bitiş");

        btnRaporla.setText("Raporla");
        btnRaporla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaporlaActionPerformed(evt);
            }
        });

        tblSatisRapor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "SepetID", "Toplam Tutar", "Musteri Adı", "Tarih"
            }
        ));
        jScrollPane1.setViewportView(tblSatisRapor);

        lblToplamFiyat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblToplamFiyat.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblToplamFiyat.setText("0 TL");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Toplam :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRaporla)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblToplamFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRaporla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblToplamFiyat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    String sumtf = null;
    private void btnRaporlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaporlaActionPerformed

        java.util.Date dt1, dt2;

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        dt1 = jDateChooser2.getDate();
        dt2 = jDateChooser3.getDate();
        String strdt1 = (String) sdf.format(dt1);
        String strdt2 = (String) sdf.format(dt2);
        

        DefaultTableModel dm = new DefaultTableModel();
        dm.addColumn("SepetID");
        dm.addColumn("Toplam Tutar");
        dm.addColumn("Musteri Adi");
        dm.addColumn("Tarih");

        String query1 = "select * from siparis where satarih between '" + strdt1 + "' and '" + strdt2 + "' ";
        String query2 = "select sum(toplamfiyat) as sumtf from siparis where satarih between '" + strdt1 + "' and '" + strdt2 + "' ";

        try {
            ResultSet rs = new MYSQLDB().baglan().executeQuery(query1);

            while (rs.next()) {
                dm.addRow(new String[]{rs.getString("srefkodu"),
                    rs.getString("toplamfiyat"),
                    rs.getString("mid"),
                    rs.getString("satarih")});
            }

            tblSatisRapor.setModel(dm);

        } catch (Exception e) {
            System.err.println("Data1 getirme hatasi " + e);
        }

        try {
            ResultSet rs2 = new MYSQLDB().baglan().executeQuery(query2);

            while (rs2.next()) {

                sumtf = rs2.getString("sumtf");
            }

            System.out.println("Sum " + sumtf);
            lblToplamFiyat.setText(sumtf + " TL");

        } catch (Exception e) {
            System.err.println("Data2 getirme hatasi " + e);
        }
    }//GEN-LAST:event_btnRaporlaActionPerformed

    public void satisRaporuDataGetir(){
        DefaultTableModel dm = new DefaultTableModel();
        dm.addColumn("SepetID");
        dm.addColumn("Toplam Tutar");
        dm.addColumn("Musteri Adi");
        dm.addColumn("Tarih");

        String query1 = "select * from siparis";

        try {
            ResultSet rs = new MYSQLDB().baglan().executeQuery(query1);

            while (rs.next()) {
                dm.addRow(new String[]{rs.getString("srefkodu"),
                    rs.getString("toplamfiyat"),
                    rs.getString("mid"),
                    rs.getString("satarih")});
            }

            tblSatisRapor.setModel(dm);

        } catch (Exception e) {
            System.err.println("Data1 getirme hatasi " + e);
        }
    }
    
    
    public void satisRaporuToplamDataGetir(){
        
        try {
            String query2 = "select sum(toplamfiyat) as sumtf from siparis ";
            ResultSet rs2 = new MYSQLDB().baglan().executeQuery(query2);
            
            while (rs2.next()) {

                sumtf = rs2.getString("sumtf");
            }

            System.out.println("Sum " + sumtf);
            lblToplamFiyat.setText(sumtf + " TL");

        } catch (Exception e) {
            System.err.println("Data2 getirme hatasi " + e);
        }
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SatisRaporu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SatisRaporu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SatisRaporu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SatisRaporu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SatisRaporu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRaporla;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblToplamFiyat;
    private javax.swing.JTable tblSatisRapor;
    // End of variables declaration//GEN-END:variables
}
